### ISSUE TITLE
The sandbox is not in sync with the Podfile.lock

### ISSUE THREAD

**Issue by obabichev** [artemyarulin/react-native-eval#4]
There is problem to add react-native-eval to react-native project.

Project structure:
├── android
├── index.android.js
├── index.ios.js
├── ios
│   ├── MCMReact
│   ├── MCMReact.xcodeproj
│   ├── MCMReact.xcworkspace
│   ├── MCMReactTests
│   ├── Podfile
│   ├── Podfile.lock
│   ├── Pods
│   └── build
├── node_modules
│   ├── react
│   ├── react-native
│   ├── react-native-eval
│   └── realm
├── package.json

My steps:
1) npm install --save react-native-eval
2) add pod to Podfile: pod 'react-native-eval',:path => '../node_modules/react-native-eval'
3) delete ios/Podfile.lock, ios/Pods
4) pod install (or pod update)

but if we try to build it we got an error:
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

We have no ideas, how to solve it. We believe that there are any conflicts with Podfile.lock in node_modules/react-native-eval but we are not sure.

Thank you for your attention.

**Comment by artemyarulin** [comment]
Hello, thanks for reporting this. Have you tried automatic installation? `npm install react-native-eval && react-native link react-native-eval` ?

**Comment by obabichev** [comment]
Yes, I have tried it. First of all I tried automatic installation because it is the easiest way, but it had the same result

**Comment by obabichev** [comment]
offtop: 
I tried manually add RNMEvaulator.h, RNMEvaulator.m to ./ios and RNMEvaulator.js to root folder.
From index.ios.js I call require('./RNMEvaluator'); without porblems and ios project compiled.
After that app works correctly but call like
NSLog(@"Bridge::::start");
  [RNMEvaluator callSyncFunction:bridge
                            name:@"Math.pow"
                            args:@[]
                              cb:^(NSString *error, id returnValue) {
                                if (error)
                                  NSLog(@"Error occured:::: %@", error);
                                else
                                  NSLog(@"Function returned:::: %@", returnValue);
                              }];
from objectiveC to js doesn't work. Method execute from RNMEvaulator.js is not called.

And I can't find reasons why It shouldn't work. May be I missed something valuable?

**Comment by artemyarulin** [comment]
Oh yeah,  I've fixed it in master with https://github.com/artemyarulin/react-native-eval/commit/adcc3959e43a19e7295e64e4860b4420524d0ab6 where I dropped Cocoapods integration in favour of `react-native link`  but forgot to push the update to NPM. May I ask you to try master version `npm install artemyarulin/react-native-eval --save && react-native link react-native-eval` ?

**Comment by obabichev** [comment]
Thank you very much, It works. ^_^ I have no problems with cocoa pods now.

**Comment by artemyarulin** [comment]
Thank you for the bug report. I'll release new version to NPM and update README when I have time
