### ISSUE TITLE
Async/await javascript function

### ISSUE THREAD

**Issue by obabichev** [artemyarulin/react-native-eval#6]
Firstly I decided that "callAsyncFunction" should correctly eval async/await functions but if I right that's not right...

And if i try to call function like 
```
async function getTestData() {
    try {
        let response = await fetch('https://api.nasa.gov/planetary/apod?api_key=NNKOjkoul8n1CH18TWA9gwngW1s1SmjESPjNoUFo');
        return await response.json();
    } catch (error) {
        console.error('JS:NASA:' + error);
    }
}
```
I get json of Promise in objectiveC.

What is the right way to call async/await functions?

It can be fixed by adding promises check to your library:
```
var execute = (data, executor) => {
    var {name, args, callId} = data,
        cb = res => {
            if (res instanceof Promise) {
                res.then(result => RNMEvaluator.functionCallCompleted(callId, null, {_value: result}));
                return;
            }
            if (res instanceof Error) {
                RNMEvaluator.functionCallCompleted(callId, `Function ${name} raised an error ${res.message}:${res.stack}`, null);
            } else {
                RNMEvaluator.functionCallCompleted(callId, null, {_value: res});
            }
        }, func, err;
```
but maybe there is a better approach?

**Comment by artemyarulin** [comment]
Hi, another way could be wrapping your function with another anonymous function (in a same way like in README example) like that:

``` javascript
function(cb) {
  getTestData()
    .then(data => cb(data))
    .catch(err => cb(err)))
}
```

But I like your idea. I'm a bit busy right now with another things, so if you make a PR - I will be happy to merge it :)

**Comment by artemyarulin** [comment]
Closed via https://github.com/artemyarulin/react-native-eval/commit/f503de8bb91fdd29f4459b6e354d0d11ff23fc24
