### ISSUE TITLE
How to use plugin

### ISSUE THREAD

**Issue by mtwallet** [artemyarulin/react-native-eval#9]
Hi @artemyarulin,

I am new to React Native and wondered if you can help me understand how I can use react-native-eval within my project? If you consider the following code:

React Native
``` JS
    // React class / method
    class MYCLASS extends Component {
      myMethod() {
        // Perform some logic
      }
      
      render() {
        return (
          // Some amount of code
        );
      }
    }
```

Main Activity
``` JAVA
    // Java code located in MainActivity
    @Override
    public void onTriggerEvent(TriggerStateChangeEvent event) {
      // How do I can run myMethod from here?
    }
```
How would I can `myMethod` from `onTriggerEvent`? `onTriggerEvent` is run when a user clicks a physical hardware button on the side of the device.

I also noticed that plugins are now initialised from within MainApplication? If this is correct would I add the package like this?

``` JAVA
    import com.evaluator.react.*; // <--- import

    public class MainApplication extends Application implements ReactApplication {

      private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        protected boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          return Arrays.<ReactPackage>asList(
              new MainReactPackage(),
                new VectorIconsPackage(),
                new MapsPackage(),
                new ReactNativeI18n(),
                new RNDeviceInfo(),
                new ReactNativeConfigPackage(),
               new RNMEPackage()
          );
        }
      };

      @Override
      public ReactNativeHost getReactNativeHost() {
          return mReactNativeHost;
      }

      @Override
      public void onCreate() {
        super.onCreate();

        SoLoader.init(this, /* native exopackage */ false);
      }
    }
```

And then add the rest of the code in my `onCreate` in MainActivity?

**Comment by artemyarulin** [comment]
Hi, in your case I'm thinking that maybe there is no need of react-native-eval. Are you going to show React Native view when onTriggerEvent has triggered? If yes, then just do normal RN initialisation (you can pass additional parameters to root view if you want). 

And sorry - I'm iOS guy, reading Java gives me headache 😄 Android version was added by other contributers, so unfortunately cannot help you with that

**Comment by mtwallet** [comment]
Hi @artemyarulin I share your pain! Having said that I've not much experience with iOS but I can tell you I had a much better time developing a React Native project for iOS.

The device I'm developing for is quite niche its an Android device with an integrated barcode scanner. It has a button on the side of the case that triggers the laser. Its this button I want to use to also trigger a React Native method. So I can't see any other than using this plugin.

I have another method that exposes the barcode value that I use in React Native however. I am storing the value in `this.state` is there a way to effectively watch that value in the app and if it changes trigger another React Native method?

**Comment by artemyarulin** [comment]
I guess you can use second parameter callback for setState function  and do any additional work there
https://facebook.github.io/react/docs/react-component.html#setstate

**Comment by mtwallet** [comment]
Thanks @artemyarulin I didn't know you could do that I'll look into that.

**Comment by artemyarulin** [comment]
You are welcome, I'll close this issue, feel free to reopen it if you think there is a need to that
